FROM thrift:0.12.0
COPY ./go1.22.1.linux-amd64.tar.gz /

WORKDIR /

RUN rm -rf /usr/local/go \
    && ls go1.22.1.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.io

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        openssl \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./ /social-network-microservices

WORKDIR /social-network-microservices
RUN go mod download \
    && go build -C src/ComposePostService-go \
    && go build -C src/TextService-remote \
    && cp src/ComposePostService-go/ComposePostService-go /usr/local/bin/ComposePostService
