name: user-timeline-service
nodeName: cpu-16

ports:
  - port: 9090
    targetPort: 9090
hostPID: true

container:
  command: UserTimelineService
  image: yxlee/socialnetwork-profile #deathstarbench/social-network-microservices
  name: user-timeline-service
  ports: 
  - containerPort: 9090

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config
