global:
  nameOverride: ""
  fullnameOverride: ""
  mainChart: hotelres
  replicas: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: Always
  serviceType: ClusterIP
  dockerRegistry: docker.io
  defaultImageVersion: ubuntu
  serviceDnsDomain: "cluster.local"
  resources: |
    requests:
      cpu: "1000m"
    limits:
      cpu: "32000m"
  services:
    environments:
      # TLS enablement
      #  - 0: Disable
      #  - 1: Enabled, using default cipher suite based on golang runtime
      #  - TLS_XXX: Enabled, using the specified Cipher suite, see tls/options.go#L22
      TLS: 0
      LOG_LEVEL: "INFO"
      JAEGER_SAMPLE_RATIO: "1"
      MEMC_TIMEOUT: "2"
      GC: "100"
  affinity: {}
  tolerations: []
  nodeSelector: {kubernetes.io/hostname: "cpu-16"}
  memcached:
    HACount: 1
    environments:
      MEMCACHED_CACHE_SIZE: "512"
      MEMCACHED_THREADS: "4"
  mongodb:
    persistentVolume:               # use hostPath or pvprovisioner
      enabled: true
      size: "10Gi"
      hostPath:
        enabled: false
        path: /tmp
      pvprovisioner:
        enabled: true
        storageClassName: openebs-hostpath   # optional
