name: frontend
serviceType: NodePort

ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32080

container:
  command: ./frontend
  image: yxlee/hotel-reservation
  name: hotel-reserv-frontend
  ports:
  - containerPort: 5000

configMaps:
  - name: service-config.json
    mountPath: config.json
    value: service-config
